config/routes.rb
Rails.application.routes.draw do
  root 'users#index'

  resources :users, only: %i[index create]
  resources :workouts
  resources :exercises
  resources :sessions, only: [:create]

  get 'create_workout' => 'workout#create'
  get 'log_out' => 'sessions#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/exercise.rb
class Exercise < ApplicationRecord
  validates :name, presence: true

  belongs_to :workout
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  has_secure_password
  has_many :workouts, dependent: :destroy

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i.freeze
  validates :name, :email, presence: true
  validates :email, format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false }
end

app/models/workout.rb
class Workout < ApplicationRecord
  validates :date, presence: true

  belongs_to :user
  has_many :exercises, dependent: :destroy
  accepts_nested_attributes_for :exercises, allow_destroy: true, reject_if: proc{ |attr| attr['name'].blank?}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :null_session
  def current_user
    User.find(session[:user_id]) if session[:user_id]
  end

  def require_login
    unless session[:user_id]
      flash[:errors] = ['Login first']
      redirect_to root_path
    end
  end
end

app/controllers/exercises_controller.rb
class ExercisesController < ApplicationController
  # GET /exercises/new
  def new
    @exercise = Exercise.new
  end

  # GET /exercises/1/edit
  def edit; end

  # POST /exercises
  # POST /exercises.json
  def create
    @exercise = Exercise.new(exercise_params)

    respond_to do |format|
      if @exercise.save
        format.html { redirect_to @exercise, notice: 'Exercise was successfully created.' }
        format.json { render :show, status: :created, location: @exercise }
      else
        format.html { render :new }
        format.json { render json: @exercise.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @exercise.update(exercise_params)
        format.html { redirect_to @exercise, notice: 'Exercise was successfully updated.' }
        format.json { render :show, status: :ok, location: @exercise }
      else
        format.html { render :edit }
        format.json { render json: @exercise.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /exercises/1
  # DELETE /exercises/1.json
  def destroy
    @exercise.destroy
    respond_to do |format|
      format.html { redirect_to exercises_url, notice: 'Exercise was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_exercise
    @exercise = Exercise.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def exercise_params
    params.require(:exercise).permit(:name, :reps, :weight, :weight_unit, :hours, :minutes, :seconds)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    user = User.find_by(email: params[:email])
    if user&.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to workouts_path
    else
      flash[:errors] = ['Invalid Combination']
      redirect_to root_path
    end
  end

  def destroy
    reset_session
    redirect_to :root
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @user = User.new
  end

  def create
    user = User.new(user_params)
    if user.save
      session[:user_id] = user.id
      redirect_to workouts_path
    else
      flash[:errors] = @user.errors.full_messages
      redirect_to :back
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/controllers/workouts_controller.rb
# frozen_string_literal: true

class WorkoutsController < ApplicationController
  before_action :require_login

  def index
    @workouts = current_user.workouts.order(:date)
    @workouts_by_date = @workouts.group_by(&:date)
    @date = params[:date] ? Date.parse(params[:date]) : Date.today
  end

  def show
    @workout = current_user.workouts.find(params[:id])
    @formatted_workout_date =
      "#{current_user.workouts.find(params[:id]).date.strftime('%B')}, #{current_user.workouts.find(params[:id]).date.day}, #{current_user.workouts.find(params[:id]).date.year}"
  end

  def new
    @workout = current_user.workouts.build(date: Date.today)
  end

  def create
    @workout = current_user.workouts.build(workout_params)
    if @workout.save
      redirect_to workouts_path, notice: 'Workout was successfully created.'
    else
      @errors = @workout.errors.full_messages
      redirect_to new_workout_path, notice: @errors
    end
  end

  def edit
    @workout = current_user.workouts.find(params[:id])
  end

  def update
    @workout = current_user.workouts.find(params[:id])
    @updated_workout = @workout.update_attributes(workout_params)
    if @updated_workout.save
      redirect_to workout_path(@workout), notice: 'Workout Updated'
    else
      @errors = @workout.errors.full_messages
      redirect_to edit_workout_path
    end
  end

  def destroy
    workout = current_user.workouts.find(params[:id])
    workout.destroy
    redirect_to workouts_path, notice: "Deleted Workout On: #{workout.date}"
  end

  private

  def workout_params
    params.fetch(:workout, {}).permit(:date, exercises_attributes: %i[_destroy id name reps weight weight_unit hours minutes seconds])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/calendar_helper.rb
# thanks Railscasts - http://railscasts.com/episodes/213-calendars-revised

module CalendarHelper
  def calendar(date = Date.today, &block)
    Calendar.new(self, date, block).table
  end

  class Calendar < Struct.new(:view, :date, :callback)
    HEADER = %w[Sunday Monday Tuesday Wednesday Thursday Friday Saturday].freeze
    START_DAY = :sunday

    delegate :content_tag, to: :view

    def table
      content_tag :table, class: 'calendar' do
        header + week_rows
      end
    end

    def header
      content_tag :tr do
        HEADER.map { |day| content_tag :th, day }.join.html_safe
      end
    end

    def week_rows
      weeks.map do |week|
        content_tag :tr do
          week.map { |day| day_cell(day) }.join.html_safe
        end
      end.join.html_safe
    end

    def day_cell(day)
      content_tag :td, view.capture(day, &callback), class: day_classes(day)
    end

    def day_classes(day)
      classes = []
      classes << 'today' if day == Date.today
      classes << 'notmonth' if day.month != date.month
      classes.empty? ? nil : classes.join(' ')
    end

    def weeks
      first = date.beginning_of_month.beginning_of_week(START_DAY)
      last = date.end_of_month.end_of_week(START_DAY)
      (first..last).to_a.in_groups_of(7)
    end
  end
end

app/helpers/exercises_helper.rb
module ExercisesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/workouts_helper.rb
module WorkoutsHelper
end

app/views/exercises/index.html.erb
<h1>Exercises</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Log_Fit</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <link rel="icon" type="image/png" href="/assets/favicon.png">
  </head>

  <body>
    <div class="bg">
      <nav class="navbar navbar-expand-lg navbar-light">
        <a class="navbar-brand" href="/workouts"><img src="/assets/favicon.png" style="height: 20px" alt="Log_Fit"></a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon na"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarText">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <div class="nav-link"><%= link_to 'Workout Log', workouts_path %></div>
            </li>
            <li class="nav-item">
              <div class="nav-link"><%= link_to 'New Workout', new_workout_path %></div>
            </li>
            <li class="nav-item">
              <div class="nav-link"><%= link_to 'Log Out', log_out_path %></div>
            </li>
          </ul>
          <span class="navbar-text">

            <!-- Fix line Below With: User.find_by(id: session[:user_id]).name-->
            <h6 class="user-text"><%= "User: #{}" %></h6>
          </span>
        </div>
      </nav>
      <div class="container-fluid align-items-center justify-content-center">
        <%= yield %>
      </div>
    </div>
  </body>
</html>

app/views/users/index.html.erb
<% if flash[:errors] %>
  <div class="row">
    <% flash[:errors].each do |e| %>
      <p class="text-danger"><%= e %></p>
    <% end %>
  </div>
<% end %>

<!-- Registration -->
<div class='row'>
  <div id="registration" class="col-md-6">
    <h1>Register</h1>
    <%= form_for @user do |f| %>
      <div class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name %>
      </div>
      <div class="form-group">
        <%= f.label :email %>
        <%= f.email_field :email %>
      </div>
      <div class="form-group">
        <%= f.label :password %>
        <%= f.password_field :password %>
      </div>
      <div class="form-group">
        <%= f.label :password_confirmation %>
        <%= f.password_field :password_confirmation %>
      </div>
      <%= f.submit %>
    <% end %>
  </div>

  <!-- Login -->
  <div id="login" class="col-md-6">
    <h1>Login</h1>
    <%= form_tag sessions_path do %>
      <div class="form-group">
        <%= label_tag :email %>
        <%= email_field_tag :email %>
      </div>
      <div class="form-group">
        <%= label_tag :password %>
        <%= password_field_tag :password %>
      </div>
      <%= submit_tag 'Sign in' %>
    <% end %>
  </div>
</div>

app/views/workouts/_exercise_fields.html.erb
<div class="nested-fields">
  <div class="form-group">
    <div class="form-inline">
      <div class="container-fluid row align-items-center">
        <%= form.hidden_field :destroy %>
        <%= form.text_field :name, placeholder: 'Exercise Name', class: 'form-control' %>
        <%= form.text_field :reps, placeholder: 'Reps/Distance', class: 'form-control' %>
        <%= form.text_field :weight, placeholder: 'Weight', class: 'form-control' %>
        <%= form.text_field :weight_unit, placeholder: 'Unit', class: 'form-control' %>
        <%= form.number_field :hours, placeholder: 'Hours', class: 'form-control' %>
        <%= form.number_field :minutes, placeholder: 'Minutes', class: 'form-control' %>
        <%= form.number_field :seconds, placeholder: 'Seconds', class: 'form-control' %>
        <button class="btn btn-outline-dark">
          <%= link_to "Remove", "#", data: { action: "click->nested-form#remove_association" } %>
        </button>
      </div>
    </div>
  </div>
</div>

app/views/workouts/_form.html.erb
<div class="container-fluid form">
  <%= form_with(model: @workout) do |form| %>
    <% if @workout.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@workout.errors.count, "error") %> prohibited this workout from being saved:</h2>

        <ul>
          <% @workout.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="container-fluid align-items-center">
      <%= form_for @workout do |f| %>
        <div class="form-group">
          <h2><%= f.label :date %></h2>
          <div class="workout_form_date"><%= f.date_field :date %></div>
        </div>
      <% end %>

      <div class="container-fluid">
        <div data-controller="nested-form">
          <br><br>
          <h2>Exercises</h2>
          <template data-target="nested-form.template">
            <%= form.fields_for :exercises, Exercise.new, child_index: 'TEMPLATE_RECORD' do |exercise| %>
              <%= render 'exercise_fields', form: exercise %>
            <% end %>
          </template>

          <%= form.fields_for :exercises do |exercise| %>
            <%= render 'exercise_fields', form: exercise %>
          <% end %>

          <div data-target="nested-form.add_exercise">
            <br>
            <%= link_to "Add Exercise", "#", data: { action: "nested-form#add_association" } %>
          </div>
        </div>
      </div>

      <br><br>

      <div class="actions" >
        <%= form.submit %>
      </div>
    </div>
  <% end %>
</div>

app/views/workouts/edit.html.erb
<h1>Edit Workout</h1>

<%= render partial: 'form' %>

app/views/workouts/index.html.erb
<h1 class="workout_title">Workouts</h1>

<div id="workouts" class="container-fluid">
  <h1 id="month">
    <%= link_to "<", date: @date.prev_month %>
    <%= @date.strftime("%B %Y") %>
    <%= link_to ">", date: @date.next_month %>
  </h1>
  <%= calendar @date do |date| %>
    <%= date.day %>
    <% if @workouts_by_date[date] %>
      <ul>
        <% @workouts_by_date[date].each do |workout| %>
          <li><%= link_to workout.date.strftime("%m/%d/%Y"), workout %></li>
        <% end %>
      </ul>
    <% end %>
  <% end %>
</div>

app/views/workouts/new.html.erb
<div novalidate class="md-layout m-5 text-center" style="padding: 25px; border: 5px solid slategray;">
  <h1>New Workout</h1>
  <br><br>
  <div class="form-group">
    <%= render partial: 'form' %>
  </div>
</div>

app/views/workouts/show.html.erb
<div class="container-fluid text-center">
  <h1><%= @formatted_workout_date %></h1>

  <h3>Exercises</h3>

  <table class="table table-dark table-striped">
    <thead>
    <tr>
      <th scope="col">Name</th>
      <th scope="col">Reps</th>
      <th scope="col">Weight</th>
      <th scope="col">Unit</th>
      <th scope="col">Time</th>
    </tr>
    </thead>

    <tbody>
    <% @workout.exercises.each do |exercise| %>
      <tr>
        <td><%= exercise.name %></td>
        <td><%= exercise.reps %></td>
        <td><%= exercise.weight %></td>
        <td><%= exercise.weight_unit %></td>
        <td><%=
          if exercise.hours.blank? && exercise.minutes.blank? && exercise.seconds.blank?
            ""
          else
            "#{exercise.hours}:#{exercise.minutes}:#{exercise.seconds}"
          end%>
        </td>
      </tr>
    <% end %>
    </tbody>
  </table>

  <div class="col">
    <ul>
      <li><%= link_to "Back", workouts_path %></li>
      <li><%= link_to "Edit", edit_workout_url(@workout) %></li>
      <li><%= link_to "Delete", workout_path(@workout), data: {
          confirm: "Are you sure you want to delete the workout on: #{@workout.date}?",
      }, method: :delete %></li>
    </ul>
  </div>
</div>